const productConstants = {
  FILTER_BY_SIZE: "FILTER_BY_SIZE",
  FILTER_BY_BRAND: "FILTER_BY_BRAND",
  FILTER_BY_GENDER: "FILTER_BY_GENDER",
  SORT_BY_PRICE: "SORT_BY_PRICE",
  CLEAR_FILTERS: "CLEAR_FILTERS",
};

export { productConstants };
